version: '2'
services:
  dbmain:
    container_name: db
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: main
    ports:
      - 54321:5432
    volumes:
      - ./.data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 18080:8080
