version: '3'
services:
  ts:
    container_name: ts
    build: .
    command: sh -c "npm run typeorm:dev migration:run && npm run start:dev"
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db_postgres
    links:
      - db_postgres
    networks:
      - ts_network

  db_postgres:
    container_name: db_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - ${DB_PORT_EXT}:5432
    volumes:
      - ./data_volumes/postgres:/var/lib/postgresql/data
    networks:
      - ts_network

networks:
  ts_network:
