version: '2'
services:
  dbmain:
    container_name: dbmain
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: main
    ports:
      - 54321:5432
    volumes:
      - ./.data:/var/lib/postgresql/data